
import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  // Cover Page Styles
  coverPage: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 60,
    fontFamily: 'Helvetica',
    justifyContent: 'space-between',
    minHeight: '100vh',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logo: {
    width: 150,
    height: 'auto',
    objectFit: 'contain',
  },
  coverContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  coverTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 1.3,
  },
  coverSubtitle: {
    fontSize: 16,
    color: '#6b7280',
    marginBottom: 40,
    textAlign: 'center',
    lineHeight: 1.5,
  },
  coverFooter: {
    borderTop: 2,
    borderTopColor: '#8B5CF6',
    paddingTop: 20,
    alignItems: 'center',
  },
  coverDate: {
    fontSize: 12,
    color: '#9ca3af',
    textAlign: 'center',
  },
  
  // Table of Contents Styles
  tocPage: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  tocTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 30,
    borderBottom: 2,
    borderBottomColor: '#8B5CF6',
    paddingBottom: 15,
  },
  tocItem: {
    fontSize: 12,
    color: '#374151',
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tocDots: {
    flex: 1,
    borderBottom: 1,
    borderBottomColor: '#e5e7eb',
    marginHorizontal: 10,
    marginBottom: 3,
  },
  
  // Content Page Styles
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
    paddingTop: 60,
    paddingBottom: 80,
  },
  header: {
    position: 'absolute',
    top: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 10,
  },
  headerLogo: {
    width: 80,
    height: 'auto',
    objectFit: 'contain',
  },
  headerTitle: {
    fontSize: 10,
    color: '#6b7280',
    flex: 1,
    textAlign: 'center',
  },
  
  // Content Styles
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1f2937',
    marginTop: 25,
    marginBottom: 15,
    borderLeft: 4,
    borderLeftColor: '#8B5CF6',
    paddingLeft: 15,
  },
  heading1: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1f2937',
    marginTop: 20,
    marginBottom: 12,
  },
  heading2: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#374151',
    marginTop: 16,
    marginBottom: 10,
  },
  heading3: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4b5563',
    marginTop: 12,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#374151',
    marginBottom: 12,
    textAlign: 'justify',
  },
  listContainer: {
    marginBottom: 16,
  },
  listItem: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#374151',
    marginBottom: 6,
    marginLeft: 15,
    flexDirection: 'row',
  },
  listBullet: {
    width: 15,
    fontSize: 11,
    color: '#8B5CF6',
  },
  listText: {
    flex: 1,
  },
  blockquote: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#6b7280',
    fontStyle: 'italic',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 12,
    borderLeft: 3,
    borderLeftColor: '#8B5CF6',
    paddingLeft: 15,
    backgroundColor: '#f8fafc',
    padding: 15,
  },
  tldrBox: {
    backgroundColor: '#8B5CF6',
    color: '#ffffff',
    padding: 20,
    marginBottom: 20,
    marginTop: 10,
    borderRadius: 8,
  },
  tldrTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 12,
  },
  tldrItem: {
    fontSize: 11,
    lineHeight: 1.5,
    color: '#ffffff',
    marginBottom: 6,
    flexDirection: 'row',
  },
  tldrBullet: {
    width: 15,
    fontSize: 11,
    color: '#ffffff',
  },
  
  // Footer Styles
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTop: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
  },
  footerText: {
    fontSize: 9,
    color: '#9ca3af',
  },
  pageNumber: {
    fontSize: 9,
    color: '#9ca3af',
  },
});
