// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agbcslwigqthrlxnqbmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnYmNzbHdpZ3F0aHJseG5xYm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTM2MTYsImV4cCI6MjA2NzM4OTYxNn0.9tciRjcOCMQNlVlkjdcASHRBQr4xmFvj_ypgbP3xgQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});